### ISSUE TITLE
defined first here error

### ISSUE THREAD

**Issue by SatsCzar** [LeMaker/RPi.GPIO_BP#20]
I getting a strange erro when I do `sudo python3 setup.py install`

multiples definitions of
first defined here

here is the full log:
[RPi.GPIO_BP_log_.txt](https://github.com/LeMaker/RPi.GPIO_BP/files/10273705/RPi.GPIO_BP_log_.txt)

**Comment by bboyadzhiev-sf** [comment]
Hi, @bolsonitro!
Based on the updated [README.md in this PR](https://github.com/LeMaker/RPi.GPIO_BP/pull/19) you need to run the build like this:
CFLAGS="-fcommon" sudo python setup.py install

**Comment by SatsCzar** [comment]
Thanks
