### ISSUE TITLE
does not seem to support J12 as wiringBP does

### ISSUE THREAD

**Issue by gitterman** [LeMaker/RPi.GPIO_BP#5]
There is also some confusion which version is for BananPi and which for BananaPro.
I found some links which say to use https://github.com/LeMaker/WiringBP and others state to add a "-b bananapi" option.
The same applies to RPi.GPIO_BP.
I finally downloaded  RPi.GPIO_BP -b bananapi  for my BPi v3 but I cannot address the following Pins from Python as I can with wiringBP gpio
J12_3=28                        # GPIO.28=wiringPi.17=GPIO_8
J12_5=30                        # GPIO.30=wiringPi.19=GPIO_10
J12_6=31                        # GPIO.31=wiringPi.20=GPIO_11

**Comment by Tony-HIT** [comment]
From here https://github.com/LeMaker/RPi.GPIO_BP/blob/bananapi/source/common.c , you can see the J12 is in the code.

**Comment by gitterman** [comment]
Sorry, but looking at the code I cannot find any J12 or j12 nor definitions for GPIO28 .. GPIO31 which are the pins for J12.
Using wiringBP I can address those pins without any problem from the shell and from C.
Thus I am going to use C instead of python now.
